language: go

sudo: true

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x

branches:
  only:
    - master
    - pre-release
    - test_ppc64le

before_install:
  - sudo apt-get install -y jq

install:
  - make build
  - sudo cp out/aliyun /usr/local/bin

notifications:
    webhooks: https://oapi.dingtalk.com/robot/send?access_token=096ed387df243a6d60835aadeccc47165f3813bc7cb81cdd0cfeadfd28e3acc1
    email: false
    on_success: change
    on_failure: always
    
before_script:
  # To make it work on travis-ci.com  
  - if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then mv ../aliyun-cli /go/pkg/mod/cache/download/github.com/aliyun/; fi

script:
  - go vet ./cli/... ./command/... ./config/... ./i18n/... ./main/... ./openapi/... ./oss/... ./resource/...
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./cli/... ./command/... ./config/... ./i18n/... ./meta/... ./main/... ./openapi/... ./resource/...
  - test -z $ACCESS_KEY_ID -a -z $ACCESS_KEY_SECRET || bash ./integration/ecs_test

after_success:
  - bash <(curl -s https://codecov.io/bash)
